<?php get_header(); the_post(); $pre=isset($_GET['product'])?sanitize_text_field(wp_unslash($_GET['product'])):''; ?>
<section class="pbi-page-hero"><div class="pbi-wrap"><div class="pbi-kicker">Quick quote</div><h1 class="pbi-title">Get a Quote<span class="pbi-dot">.</span></h1><p class="pbi-sub">Choose what you need. Share the specs. We’ll confirm the best route.</p><div class="pbi-quote-steps"><div class="pbi-quote-step is-active"><div class="pbi-quote-step__n">1</div><span>Product</span></div><div class="pbi-quote-step"><div class="pbi-quote-step__n">2</div><span>Specs</span></div><div class="pbi-quote-step"><div class="pbi-quote-step__n">3</div><span>Artwork</span></div><div class="pbi-quote-step"><div class="pbi-quote-step__n">4</div><span>Contact</span></div></div></div></section>
<section class="pbi-section--tight"><div class="pbi-wrap pbi-quote-layout">
<form class="pbi-form-card" method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" data-lead-form enctype="application/x-www-form-urlencoded"><input type="hidden" name="action" value="pbi_submit_lead"><input type="hidden" name="lead_type" value="Quote request"><input type="hidden" name="product" value="<?php echo esc_attr($pre); ?>"><?php wp_nonce_field('pbi_submit_lead','pbi_nonce'); get_template_part('template-parts/lead-hidden-fields'); ?>
<h2>1. Select product</h2><div class="pbi-product-picker">
<?php $products=pbi_get_products(8); if($products->have_posts()):while($products->have_posts()):$products->the_post(); $sel=$pre===get_the_title(); ?><button type="button" class="pbi-product-choice <?php echo $sel?'is-selected':''; ?>" data-product-choice data-product="<?php the_title_attribute(); ?>"><div class="pbi-product-choice__img"><?php if(has_post_thumbnail())the_post_thumbnail('pbi-card'); ?></div><strong><?php the_title(); ?></strong></button><?php endwhile;wp_reset_postdata();endif; ?></div>
<h2 style="margin-top:28px">2. Add specifications</h2><div class="pbi-form-grid"><div class="pbi-field"><label>Quantity</label><input name="quantity" value="250" data-sync-summary></div><div class="pbi-field"><label>Size</label><input name="size" placeholder="A4 / A5 / Custom" data-sync-summary></div><div class="pbi-field"><label>Paper / material</label><input name="paper" placeholder="Premium matte / gloss" data-sync-summary></div><div class="pbi-field"><label>Finish</label><input name="finish" placeholder="Matte / gloss / custom" data-sync-summary></div></div>
<h2 style="margin-top:28px">3. Artwork & details</h2><div class="pbi-upload">Have artwork ready? Mention the file name below and our team will share the secure upload route after submission.</div><div class="pbi-form-grid" style="margin-top:14px"><div class="pbi-field pbi-field--full"><label>Artwork / reference name</label><input name="artwork_name" placeholder="e.g. company-brochure-final.pdf"></div><div class="pbi-field"><label>Name *</label><input name="name" required></div><div class="pbi-field"><label>Phone *</label><input name="phone" required></div><div class="pbi-field"><label>Email</label><input type="email" name="email"></div><div class="pbi-field"><label>Company</label><input name="company"></div><div class="pbi-field pbi-field--full"><label>Anything else?</label><textarea name="message" rows="4"></textarea></div></div><button class="pbi-btn pbi-btn--primary" style="width:100%;margin-top:16px" type="submit">Submit Quote Request ↗</button></form>
<aside class="pbi-form-card pbi-summary"><div class="pbi-kicker">Your request</div><h2 data-summary-product><?php echo esc_html($pre ?: 'Select a product'); ?></h2><dl><div><dt>Quantity</dt><dd data-summary="quantity">250</dd></div><div><dt>Size</dt><dd data-summary="size">—</dd></div><div><dt>Paper</dt><dd data-summary="paper">—</dd></div><div><dt>Finish</dt><dd data-summary="finish">—</dd></div></dl><div class="pbi-notice">No guessed pricing here. We’ll confirm the quote after reviewing quantity, material, finishing and artwork.</div><div style="margin-top:14px"><a class="pbi-btn pbi-btn--outline" style="width:100%" target="_blank" rel="noopener" href="https://wa.me/<?php echo esc_attr(preg_replace('/\D+/','',pbi_contact('whatsapp','919876543210'))); ?>">Need help? WhatsApp us</a></div></aside>
</div></section>
<?php get_footer(); ?>
